services:
    kv:
        build:
            context: kv
            dockerfile: kv.dockerfile
        volumes:
            - ./auth/public.pem:/tmp/public.pem
        command:
            [
                "python3",
                "kv.py",
                "--public",
                "/tmp/public.pem",
                "--port",
                "8090"
            ]
        ports:
            - 8091:8090

    auth:
        build:
            context: auth
            dockerfile: auth.dockerfile
        volumes:
            - ./auth/private.pem:/tmp/private.pem
            - ./auth/public.pem:/tmp/public.pem
        command:
            [
                "python3",
                "auth.py",
                "--private",
                "/tmp/private.pem",
                "--public",
                "/tmp/public.pem",
                "--port",
                "8090"
            ]
        ports:
            - 8090:8090
        depends_on:
            - kv

    tests:
        build:
            context: tests
        environment:
            KV_SERVER_URL: "http://kv:8090"
            AUTH_SERVER_URL: "http://auth:8090"
            JWT_PRIVATE_KEY_FILE: "/tmp/private.pem"
            JWT_PUBLIC_KEY_FILE: "/tmp/public.pem"
        volumes:
            - ./auth/private.pem:/tmp/private.pem
            - ./auth/public.pem:/tmp/public.pem
        depends_on:
            - auth
            - kv
