version: "3"

services:
    rabbitmq:
        image: rabbitmq:3-management
        hostname: "rabbitmq"
        ports:
            - "15672:15672"
            - "5672:5672"
    web:
        build:
            context: server
        environment:
            RABBITMQ_HOST: "rabbitmq"
            RABBITMQ_PORT: "5672"

            WEB_HOST: "0.0.0.0"
            WEB_PORT: "5000"
            DATA_DIR: "/data"
        volumes:
            # do not remove these volumes
            - /var/run/docker.sock:/tmp/docker.sock
            - data-volume:/data
        expose:
            - 5000
        depends_on:
            - rabbitmq
    worker:
        build:
            context: worker
        environment:
            RABBITMQ_HOST: "rabbitmq"
            RABBITMQ_PORT: "5672"

            DATA_DIR: "/data"
        volumes:
            # do not remove these volumes
            - /var/run/docker.sock:/tmp/docker.sock
            - data-volume:/data
        depends_on:
            - rabbitmq
    pytest:
        build: tests/
        volumes:
            # do not remove these volumes
            - /var/run/docker.sock:/tmp/docker.sock
            - data-volume:/data
        depends_on:
            - rabbitmq
            - web
            - worker

volumes:
    data-volume:
