name: HW 9

on:
  push:
    branches: ["2023"]
    paths: ["homework/09-kv-replication-v2/**"]
  pull_request:
    branches: ["2023", "master"]
    paths: ["homework/09-kv-replication-v2/**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    if: github.repository != 'osukhoroslov/distsys-course-hse'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
           workspaces: homework/09-kv-replication-v2/tests
           cache-on-failure: true
      - name: Run tests
        working-directory: homework/09-kv-replication-v2/tests
        run: cargo run --release
